---
title: "Crime and Punishment Text Analysis"
author: "Kayla Choi"
date: "12/8/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("book_read.R")
```

## Task 2: Bag of Words
  
I chose to analyze Crime and Punishment by Fyodor Dostoevsky. This is one of my favorite books out of the ones I had to read in high school.   
I downloaded the txt file from the Gutenberg Project. Excluding the foreword and the ending citation of Gutenberg project, I turned it into a tibble. 
  
  
Generally, the visualization of the sentiment analysis matches the plotline of the book. The book is split into 6 parts with 1 epilogue. In the first part, the protagonist Raskolnikov commits murder; the next 5 parts describe in detail the moral anguish that Raskolnikov faces and the slow hunt as the detective gets closer to figuring him out. It makes sense that the sentiment through most of the book is negative. I was surprised to see that there wasn't much a huge positive sentiment difference at the very end of the book. In the epilogue, Raskolnikov confesses to his crime, and though he ends up in prison, he begins to accept unconditional love from Sonya and turns towards religion to start his journey towards redemption and moral restitution. That's why I anticipated seeing such a large positive spike at the end, since it is the first time in the book where he is open to concepts such as "friendliness" and "love" and "redemption." However, it makes sense that there isn't a huge peak because he is still in prison, so the words probably pick up on that as a negative sentiment.    
  